---
title: EEE933 - Design and Analysis of Experiments

# Use letters for affiliations
author:
  - name: Case Study 01

# For footer text  TODO(fold into template, allow free form two-authors)
#lead_author_surname: ELE077 - TC1

# Place DOI URL or CRAN Package URL here
#doi: "https://cran.r-project.org/package=YourPackage"

# Abstract
abstract: |
  Experiment: performance of a new software version.

# Optional: Acknowledgements
# acknowledgements: |
#   This template package builds upon, and extends, the work of the excellent 
#   [rticles](https://cran.r-project.org/package=rticles) package, and both rely on
#   the [PNAS LaTeX](http://www.pnas.org/site/authors/latex.xhtml) macros. Both sources
#   are gratefully acknowledged as this work would not have been possible without them.
#   Our extensions are under the same respective licensing term 
#   ([GPL-3](https://www.gnu.org/licenses/gpl-3.0.en.html) and
#   [LPPL (>= 1.3)](https://www.latex-project.org/lppl/)).

# Optional: One or more keywords
# keywords:
#   - one
#   - two
#   - optional
#   - keywords
#   - here

# Font size of the document, values of 9pt (default), 10pt, 11pt and 12pt
fontsize: 11pt

# Optional: Force one-column layout, default is two-column
one_column: true

# Optional: Enables lineo mode, but only if one_column mode is also true
#lineno: true

# Optional: Enable one-sided layout, default is two-sided
#one_sided: true

# Optional: Enable section numbering, default is unnumbered
#numbersections: true

# Optional: Specify the depth of section number, default is 5
#secnumdepth: 5

# Optional: Bibliography 
#bibliography: pinp

# Optional: Enable a 'Draft' watermark on the document
#watermark: true

# Customize footer, eg by referencing the vignette
#footer_contents: "YourPackage Vignette"

# Optional: Skip inserting final break between acknowledgements, default is false
skip_final_break: true

# Produce a pinp document
output: pinp::pinp


# Required: Vignette metadata for inclusion in a package.
#vignette: >
#  %\VignetteIndexEntry{YourPackage-vignetteentry}
#  %\VignetteKeywords{YourPackage, r, anotherkeyword}
#  %\VignettePackage{YourPackage}
#  %\VignetteEngine{knitr::rmarkdown}
---


# The experiment  

The **current** version of a software used for simulating certain electromagnetic characteristics of a patch antenna is known, based on extensive past experience, to have a mean simulation time of $\mu = 55s$ seconds and a variance $\sigma^2 = 100s^2$.

A **new** version of this software is developed, and we wish to investigate whether it results in _performance gains_ (i.e., smaller mean runtime and/or smaller variance) in relation to the current standard. To investigate this particular question, $14$ simulations are executed, and their times are recorded as (`CS01_data.csv`, available on [https://git.io/vpGxG](https://git.io/vpGxG)):

```{r, echo = FALSE}
x <- read.table("CS01_data.csv", header = TRUE)
x[, 1]
```

***

# Activities  

## For the test on the mean runtime  

For this test, assume a desired significance level $\alpha = 0.01$. The teams must perform the following activities:

- Define the statistical hypotheses to be tested (null/alternative).
- Discuss and define the other experimental parameters of the test (smallest effect of practical relevance, desired power, _etc._). This is specific for each team, but must be determined based on discussions, related to the topic of the experiment.
- Test the hypotheses and decide for rejecting (or not) the null hypothesis.
- Calculate the confidence interval on the mean runtime.
- Validate and discuss the assumptions of the test.
- Discuss the power of the test (if needed), and the adequacy of the available sample size for this particular test.

## For the test on the standard deviation  

For this test, assume a desired significance level $\alpha = 0.05$. The teams must perform the following activities:

- Define the statistical hypotheses to be tested (null/alternative).
- Test the hypotheses and decide for rejecting (or not) the null hypothesis.
- Calculate the confidence interval on the variance of the runtime.
- Validate and discuss the assumptions of the test.


After performing the activities related to each test individually, the team must:

- Draw conclusions and provide recommendations regarding the adoption (or not) of the new software version.
- Discuss possible ways to improve this experiment.

***

# Report  

Each team must prepare a short report detailing the experiment and the analysis performed. The report will be evaluated according to the following criteria:

- Use of the predefined format (see below);
- Reproducibility of the analyses;
- Technical quality;
- Logical structure;
- Correct use of language (grammar, orthography, _etc._);

The report must **necessarily** be prepared using [R Markdown](http://rmarkdown.rstudio.com), and must contain the full code needed to reproduce the analysis performed by the team, embedded in the form of _code blocks_. Each team must deliver the following files:

- The report file, compiled in **.pdf** .
- The original (source) of the report, in **.Rmd**.

the **.Rmd** file must be able to be recompiled, if needed (tip: save your **.Rmd** file using UTF-8 encoding, to prevent compilation problems in other operational systems. 

Report templates are available on  [https://git.io/vHk0F](https://git.io/vHk0F), and an example of report structure can be consulted on [https://git.io/vHk0j](https://git.io/vHk0j). 

**Important**: Please include in the report the roles of each team member (Coordinator, Recorder, Checker and, for 4-member teams, Monitor)

**Important**: Reports can be prepared in either Portuguese or English.

***

# Deadline  

The report files (pdf + rmd) must be compressed into a single file and uploaded to the activity **Case Study 01** on Moodle, until **Friday, May 4th 2018, 11:59p.m.**. After that deadline the system will be closed. 

**Important**: Only ONE submission is required for each team.

**Important**: Reports will NOT be received by e-mail or in printed form.
