---
title: "Final Project"
header-includes:
   - \usepackage{framed}
output: pdf_document
---
\definecolor{shadecolor}{rgb}{0.94, 0.97, 1.0}

## Summary
The students (individually or in pairs) must choose an experimental question of interest for investigation. While designed experiments are preferred, observation or retrospective studies are also accepted. The final project consists of:

- Definition of the experimental question;
- Review of the relevant literature;
- Experimental design (for designed experiments) or data cleaning and preconditioning (otherwise);
- Data collection according to the design (for designed experiments)
- Statistical modeling and analysis of the data;
- Drawing of conclusions from the data.

## Report
The report must be prepared using the same [R Markdown template](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Report%20template) used for the case studies. The report should contain:

- Summary;
- Introduction, including the description of the _research question_ being investigated and a brief literature review on the topic;
- Experimental design, including materials and methods, data collection protocols, criteria for including/excluding observations, etc.;
- Experimental results, including any observations about the actual data gathering, exploratory data analysis, statistical inference, model validation, quantification of effect sizes, and discussion of the results;
- Conclusions and recommendations (**note**: conclusions about the _experiment_. I'm not interested in comments about "the importance of design of experiments" - I know it's important - but instead I want to know what conclusions can you draw about your question of interest.)


The report will be evaluated according to the following criteria:

- Justification for the experiment (i.e., how well you can justify your question of interest);
- Compliance with the required format;
- Reproducibility of results;
- Technical correctness and methodological soundness;
- Structure of argumentation;
- Correct use of language (grammar, orthography, etc.);

## Seminar
The student/pair will present his/her/their work in a seminar. The format for this seminar is free, but the time limit is 12 minutes. The order of the presentations will be defined randomly on the first day of the seminars.