---
title: "EEE933 - Estudo de Caso 01"
author: "BMI médio dos alunos do PPGEE"
output: html_document
---

## O Experimento
O BMI (_body mass index_, ou índice de massa corporal) é um indicador frequentemente utilizado em avaliações clínicas de questões relacionadas ao peso do índivíduo. Este índice é calculado como a razão entre o peso (em kg) e o quadrado da estatura (em metros):

$$bmi = \frac{m}{h^2}$$

e é dado em unidades de $kg/m^2$. Usualmente, o valor obtido é utilizado para classificar o indivíduo em algumas categorias [[1](http://apps.who.int/bmi/index.jsp?introPage=intro_3.html)]:

- Underweight	<18.50
	- Severe thinness	<16.00
	- Moderate thinness 16.00 - 16.99
	- Mild thinness 17.00 - 18.49
- Normal range	18.50 - 24.99
- Overweight	$\geq$ 25.00
	- Pre-obese	25.00 - 29.99
	- Obese	$\geq$ 30.00
		- Obese class I	30.00 - 34.99
		- Obese class II	35.00 - 39.99
		- Obese class III	$\geq$ 40.00

O professor Felipe Campelo, do Departamento de Engenharia Elétrica da UFMG, reporta estar atualmente com um valor de $BMI = 26.3 kg/m^2$. Neste estudo de caso vamos buscar responder à pergunta: _Os alunos do PPGEE estão, em média, mais "acima do peso" (de acordo com o BMI) do que este professor?_ Para isso, os alunos da disciplina foram solicitados a reportar seu peso e estatura de forma anonimizada, formando uma nase de dados com a qual pretende-se realizar a inferência estatística.

## Atividades

- Definição das hipóteses de teste (qual a hipótese nula? Qual a alternativa? Que tipo de teste utilizar?);
- Definição dos parâmetros experimentais desejados: nível de significância, menor tamanho de efeito de importância prática, nível de potência desejada etc..
- Consolidação dos dados coletados em uma base comum (em formato **.CSV**)
- Estimação do tamanho do efeito e do intervalo de confiança _bilateral_ na grandeza de interesse (note que deseja-se um intervalo de confiança bilateral, mesmo que a hipótese alternativa seja direcional);
- Verificação e discussão das premissas do teste;
- Derivação de conclusões e recomendações.
- Discussão sobre a potência do teste (se aplicável).
- Discussão sobre possíveis formas de melhorar este experimento.

## Relatório
Cada grupo deverá entregar um relatório detalhando o experimento e a análise dos dados. O relatório será avaliado de acordo com os seguintes critérios:

- Obediência ao formato determinado (ver abaixo);
- Reproducibilidade dos resultados;
- Qualidade técnica;
- Estrutura da argumentação;
- Correto uso da linguagem (gramática, ortografia, etc.);

O relatório deve *obrigatoriamente* ser produzido utilizando [R Markdown](http://rmarkdown.rstudio.com), e deve conter todo o código necessário para a reprodução da análise obtida, embutido na forma de blocos de código no documento. Os grupos devem enviar:

- O arquivo **.Rmd** do relatório.
- O arquivo de dados utilizado.

O arquivo **.Rmd** deve ser capaz de ser compilado em um pdf sem erros, e deve assumir que o arquivo de dados se encontra no mesmo diretório do arquivo do relatório. Modelos de estudos de caso estão disponíveis no [aqui](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Grading/Report%20template) e [aqui](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Grading/Case%20Studies/Report%20Examples). 

**Importante**: Salve seu arquivo **.Rmd** em UTF-8 (para evitar erros na compilação em outros sistemas).
**Importante**: Inclua no relatório os papéis desempenhados por cada membro da equipe (Relator, Verificador etc.)

Relatórios serão aceitos em português, inglês ou espanhol.

## Entrega
Os arquivos deverão ser enviados via _e-mail_ para o endereço [fcampelo@ufmg.br](fcampelo@ufmg.br). O título do e-mail deve seguir o padrão "**[EEE933_2016-1_EC01] Nome_da_equipe**" (sem as aspas). A data-limite para o recebimento dos arquivos é **segunda-feira (11/04) às 11:00h**
