---
title: EEE933 - Estudo de Caso 02
abstract: |
  Comparação do IMC médio de alunos do PPGEE-UFMG ao longo de um ano

# Use letters for affiliations
author:
  - name: Felipe Campelo
    affiliation: a
address:
  - code: a
    address: Programa de Pós-Graduação em Engenharia Elétrica, UFMG.

# Abstract
# abstract: |
#   Descrição do segundo estudo de caso para a disciplina de Planejamento e Análise de Experimentos do Programa de Pós-Graduação em Engenharia Elétrica da UFMG. 

# Font size of the document, values of 9pt (default), 10pt, 11pt and 12pt
fontsize: 11pt

# Optional: Force one-column layout, default is two-column
#one_column: true

# Optional: Enables lineo mode, but only if one_column mode is also true
#lineno: true

# Optional: Enable one-sided layout, default is two-sided
one_sided: true

# Optional: Enable section numbering, default is unnumbered
#numbersections: true

# Optional: Specify the depth of section number, default is 5
#secnumdepth: 5

# Optional: Bibliography 
#bibliography: pinp

# Optional: Enable a 'Draft' watermark on the document
#watermark: true

# Customize footer, eg by referencing the vignette
footer_contents: "Document created using R Markdown + PINP package"

# Produce a pinp document
output: pinp::pinp
---

## O Experimento
Neste estudo deseja-se comparar o IMC [[1](http://apps.who.int/bmi/index.jsp?introPage=intro_3.html)] médio de duas populações de estudantes, a saber: alunos de pós-graduação em Engenharia Elétrica na UFMG nos semestres 2016-2 e 2017-2. Neste caso estamos usando o IMC como um valor _proxy_ para variáveis relativas ao estilo de vida dos alunos (apesar das limitações conhecidas deste indicador [[2](http://www.nytimes.com/interactive/projects/cp/summer-of-science-2015/latest/how-often-is-bmi-misleading),[3](http://science.sciencemag.org/content/341/6148/856.summary),[4](http://www.medicalnewstoday.com/articles/265215.php)]. Assim como discutido no primeiro estudo de caso, é razoável supor que a divisão da análise em duas sub-populações (masculina e feminina) seja interessante.

Os dados relativos a uma amostra anterior dos alunos (semestre 2016-2) estão tabulados no arquivo [imc_20162.csv](https://raw.githubusercontent.com/fcampelo/Design-and-Analysis-of-Experiments/master/data%20files/imc_20162.csv), disponível na pasta _data files_ do repositório Github da disciplina; Os dados da turma atual (2017-2) estão disponíveis na mesma pasta, no arquivo [CS01_20172.csv](https://raw.githubusercontent.com/fcampelo/Design-and-Analysis-of-Experiments/master/data%20files/CS01_20172.csv).

Note que o arquivo relativo a 2016-2 contém também dados de uma turma de graduação, e que os dois arquivos (2016-2 e 2017-2) estão em formatos ligeiramente diferentes. É parte da tarefa deste estudo de caso isolar os dados de interesse e consolidar os mesmos de forma a realizar a análise de forma correta.

## Atividades

- Definição das hipóteses de teste (qual a hipótese nula? Qual a alternativa? Que tipo de teste utilizar?);
- Teste de hipóteses;
- Estimação do tamanho do efeito e do intervalo de confiança na grandeza de interesse;
- Verificação e discussão das premissas do teste;
- Derivação de conclusões e recomendações.
- Discussão sobre a potência do teste (se aplicável).
- Discussão sobre possíveis formas de melhorar este experimento.

## Relatório
Cada grupo deverá entregar um relatório detalhando o experimento e a análise dos dados. O relatório será avaliado de acordo com os seguintes critérios:

- Obediência ao formato determinado (ver abaixo);
- Reproducibilidade dos resultados;
- Qualidade técnica;
- Estrutura da argumentação;
- Correto uso da linguagem (gramática, ortografia, etc.);

O relatório deve *obrigatoriamente* ser produzido utilizando [R Markdown](http://rmarkdown.rstudio.com) (opcionalmente utilizando estilos distintos, como o do presente documento), e deve conter todo o código necessário para a reprodução da análise obtida, embutido na forma de blocos de código no documento. Os grupos devem enviar:

- O arquivo **.Rmd** do relatório.
- O arquivo de dados utilizado.

O arquivo **.Rmd** deve ser capaz de ser compilado em um pdf sem erros, e deve assumir que o arquivo de dados se encontra no mesmo diretório do arquivo do relatório. Modelos de estudos de caso estão disponíveis  [aqui](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Grading/Report%20template) e [aqui](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Grading/Case%20Studies/Report%20Examples). Caso a equipe deseje utilizar o estilo do presente documento, pode consultar seu código-fonte [aqui](https://raw.githubusercontent.com/fcampelo/Design-and-Analysis-of-Experiments/master/Semester%20files/2017-2%20(PT)/Case%20Studies/CS02.Rmd) (note que o mesmo requer a instalação do pacote _pinp_).

**Importante**: Salve seu arquivo **.Rmd** em UTF-8 (para evitar erros na compilação em outros sistemas).
**Importante**: Inclua no relatório os papéis desempenhados por cada membro da equipe (Relator, Verificador etc.)

Relatórios serão aceitos em português, inglês ou espanhol.

## Entrega
Os arquivos deverão ser enviados via _e-mail_ para o endereço [fcampelo@ufmg.br](fcampelo@ufmg.br). O título do e-mail deve seguir o padrão "**[EEE933_2017-2_EC02] Nome_da_equipe**" (sem as aspas). A data-limite para o recebimento dos arquivos é **segunda-feira (02/10) às 11:00h**
