---
title: "EEE933 - Estudo de Caso 02"
author: "Comparação do IMC médio de alunos de Eng. Sistemas e do PPGEE-UFMG"
output: pdf_document
---

## O Experimento
Neste estudo deseja-se comparar o IMC [[1](http://apps.who.int/bmi/index.jsp?introPage=intro_3.html)] médio de duas populações de estudantes, a saber: alunos de graduação em Engenharia de Sistemas e alunos de pós-graduação em Engenharia Elétrica. Neste caso estamos usando o IMC como um valor _proxy_ para variáveis relativas ao estilo de vida dos alunos (apesar das limitações conhecidas deste indicador [[2](http://www.nytimes.com/interactive/projects/cp/summer-of-science-2015/latest/how-often-is-bmi-misleading), [3](http://science.sciencemag.org/content/341/6148/856.summary), [4](http://www.medicalnewstoday.com/articles/265215.php)]). Assim como no primeiro estudo de caso, é razoável supor que a divisão da análise em duas sub-populações (masculina e feminina) seja interessante.

Os dados relativos a ambas as turmas estão tabulados no arquivo [imc_20162.csv](https://raw.githubusercontent.com/fcampelo/Design-and-Analysis-of-Experiments/master/data%20files/imc_20162.csv), disponível na pasta _data files_ do repositório Github da disciplina.  

## Atividades

- Definição das hipóteses de teste (qual a hipótese nula? Qual a alternativa? Que tipo de teste utilizar?);
- Teste de hipóteses;
- Estimação do tamanho do efeito e do intervalo de confiança na grandeza de interesse;
- Verificação e discussão das premissas do teste;
- Derivação de conclusões e recomendações.
- Discussão sobre a potência do teste (se aplicável).
- Discussão sobre possíveis formas de melhorar este experimento.

## Relatório
Cada grupo deverá entregar um relatório detalhando o experimento e a análise dos dados. O relatório será avaliado de acordo com os seguintes critérios:

- Obediência ao formato determinado (ver abaixo);
- Reproducibilidade dos resultados;
- Qualidade técnica;
- Estrutura da argumentação;
- Correto uso da linguagem (gramática, ortografia, etc.);

O relatório deve *obrigatoriamente* ser produzido utilizando [R Markdown](http://rmarkdown.rstudio.com), e deve conter todo o código necessário para a reprodução da análise obtida, embutido na forma de blocos de código no documento. Os grupos devem enviar:

- O arquivo **.Rmd** do relatório.
- O arquivo de dados utilizado.

O arquivo **.Rmd** deve ser capaz de ser compilado em um pdf sem erros, e deve assumir que o arquivo de dados se encontra no mesmo diretório do arquivo do relatório. Modelos de estudos de caso estão disponíveis  [aqui](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Grading/Report%20template) e [aqui](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Grading/Case%20Studies/Report%20Examples). 

**Importante**: Salve seu arquivo **.Rmd** em UTF-8 (para evitar erros na compilação em outros sistemas).
**Importante**: Inclua no relatório os papéis desempenhados por cada membro da equipe (Relator, Verificador etc.)

Relatórios serão aceitos em português, inglês ou espanhol.

## Entrega
Os arquivos deverão ser enviados via _e-mail_ para o endereço [fcampelo@ufmg.br](fcampelo@ufmg.br). O título do e-mail deve seguir o padrão "**[EEE933_2016-1_EC02] Nome_da_equipe**" (sem as aspas). A data-limite para o recebimento dos arquivos é **segunda-feira (19/09) às 11:00h**
