---
title: "Case Study 4"
author: "Comparison of Drilling Riser Configurations"
header-includes:
   - \usepackage{framed}
output: pdf_document
---
\definecolor{shadecolor}{rgb}{0.94, 0.97, 1.0}

## The Experiment
Drilling risers are important components of undersea oil exploration systems, responsible for transporting the oil from the ocean floor to the surface. A researcher wishes to compare the average time to failure of four configurations of risers, so that she may choose the one with the smallest probability of failure within 20 years. The researcher chooses to employ the time to failure (in minutes) obtained using scale models of the risers subject to an accelerated life testing protocol as a proxy variable for the real system.

The current standard configuration is labeled _Riser 1_, and the researcher is initially interested in knowing whether any of the other three options will provide a larger mean time to failure (MTTF) value. In order to reduce costs, available historical data for _Riser 1_ will be used. This data is known to have been obtained under the same test protocols planned for the other three configurations.

The available information about _Riser 1_ is available in the file [riser1.csv](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/blob/master/data%20files/riser1.csv). Since the distribution of times-to-failure is known to be asymptotically lognormal, the data is provided in the log scale (for the sake of simplicity, the whole analysis and the conclusions can be done without back-transformation to the linear scale).

The engineering team defined the desired characteristics for the experiment as:

- Significance: $\alpha = 0.1$;
- Minimally interesting effect: $\delta^{*} = 0.25$;
- Desired power: $(1 - \beta) \geq 0.8$;

The real variance of the process is unknown, but it is supposed to be uniform across all risers. The estimated average cost of each new observation is US$25000, but observations available from historical data are considered free.

## Activities

Based on the information given above, your task is to answer the following question: 

\begin{snugshade}
\begin{center}\textit{
Is any of the alternative risers better than the standard one?}\end{center}
\end{snugshade}

Your analysis should follow a simple procedure:

1. Describe the experimental design required to answer the technical question of interest. Detail the hypotheses being tested and the relevant design for testing those hypotheses.
2. Calculate the required sample size for the experiment. Don't forget to report the total costs of your experiment.

3. Simulate your data collection procedure using the app available [here](http://fcampelo.shinyapps.io/riserdata) or [here](http://150.164.32.10:3838/riserdata).
    - **Note**: The app will already include the historical observations for _Riser 1_ in the first lines of the resulting data file. However, you can (and probably should) examine the historical observations (also available [here](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/blob/master/data%20files/riser1.csv)) prior to your data gathering.

4. Perform the statistical analysis using the observations contained in the data file that you generated using the app. This includes:
    a. Perform the actual test of statistical significance;
    b. Estimate the effect size (including the confidence interval);
    c. Check the assumptions of your test;
    d. Describe your conclusions and recommendations.

Remember that your conclusions should always be placed in the context of the original technical/scientific question.

## Report
You must deliver a short report detailing your analysis and the results obtained.  Instructions for writing your report depend on the course you're taking, and are given below:

### For graduate (PPGEE) Students
Your report will be evaluated according to:

- Compliance with the required format (see below);
- Reproducibility of results;
- Technical correctness;
- Structure of argumentation;
- Correct use of language (grammar, orthography, etc.);

The report **must** be produced using [R Markdown](http://rmarkdown.rstudio.com), and should contain the reproducible analysis code embedded as code blocks within the document. Please send me both the **.Rmd** file and the **.csv** data file generated by the simulation app. The analysis should assume that the data file is in the same directory as the report file. 

A template for the case study reports is available in our [GitHub repo](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Report%20template).

Reports written in either Portuguese, English, or Spanish will be accepted.


### For undergrad (Systems Engineering) Students
Your report will be evaluated according to:

- Technical correctness;
- Correct use of language (grammar, orthography, etc.);

The report has no particular template. [R Markdown](http://rmarkdown.rstudio.com) is suggested, but not mandatory. Please send me the **.pdf** file (**NO** .doc, .odt, or other exotic formats please), the **.R** analysis file, and the **.csv** data file generated by the simulation app

-----
## Final tips and suggestions:
- **Tip 1**: some ways are cheaper (i.e., require smaller sample sizes) than others. Explore different possibilities and their required sample sizes before proceeding to the data collection phase.;
- **Tip 2**: [This](http://www.cscu.cornell.edu/news/statnews/stnews83.pdf) may be useful.