---
title: "Case Study 2"
author: "Comparison of accuracy in a ballistics laboratory"
header-includes:
   - \usepackage{framed}
output: pdf_document
---
\definecolor{shadecolor}{rgb}{0.94, 0.97, 1.0}

## The Experiment^[Adapted from Mason _et al._, _Statistical Design and Analysis of Experiments with Applications to Engineering and Science_, Wiley-Interscience 2003.]

A ballistics laboratory is in the process of being certified for the evaluation of shielding technology. As part of this process, the laboratory must provide evidence that a certain callibration procedure produces results that are consistent with a reference equipment from the Department of Defence.

The procedure in question consists of shooting a standardized steel cube against a 320mm-thick alluminum target and measuring the resulting hole area. From previous measurements under similar conditions, the standard deviations of the observations of this laboratory and of the Department of Defence can be roughly estimated as:

- $\hat{\sigma}_{Lab}$: 5 mm^2^
- $\hat{\sigma}_{DD}$: 10 mm^2^

The certification authority demands that the mean hole area generated by this procedure in the lab be the same as the one from the reference equipment, and tolerates deviations no greater than 4 mm^2^. Since this certification is quite important for the laboratory, the engineer in charge of the process decides that he wants a significance level $\alpha = 0.01$ and a power of $(1-\beta) = 0.9$ for the smallest effect size of practical significance. 

Assume that the engineer has free access to both the reference and the local test equipments (so that in theory he could obtain as many observations as needed), but that each observation is relatively expensive (so that in practice he wants to use the smallest sample size possible).

## Activities

Your task is to answer the following question: 

\begin{snugshade}
\begin{center}\textit{
Is the mean hole size generated by the laboratory in conformity with\\
the one generated by the reference equipment?}\end{center}
\end{snugshade}

Your analysis should follow a simple procedure:

1. Describe the experimental design required to answer the technical question of interest. Detail the hypotheses being tested and the relevant design for testing those hypotheses.
2. Calculate the required sample size for the experiment. For the sake of simplicity you can consider equal sample sizes for both .
3. Simulate your data collection procedure using the app available [here](http://fcampelo.github.io/labdata) (also available in [this mirror](http://150.164.32.10:3838/labdata) )
4. Perform the statistical analysis using the observations contained in the data file that you generated using the app. This includes:
      a. Perform the actual test of statistical significance;
      b. Estimate the effect size (including the confidence interval);
      c. Check the assumptions of your test;
      d. Describe your conclusions and recommendations.

Remember that your conclusions should always be placed in the context of the original technical/scientific question.

## Report
You must deliver a short report detailing your analysis and the results obtained.  Instructions for writing your report depend on the course you're taking, and are given below:

### 1) For graduate (PPGEE) Students
Your report will be evaluated according to:

- Compliance with the required format (see below);
- Reproducibility of results;
- Technical correctness;
- Structure of argumentation;
- Correct use of language (grammar, orthography, etc.);

The report **must** be produced using [R Markdown](http://rmarkdown.rstudio.com), and should contain the reproducible analysis code embedded as code blocks within the document. Please send me both the **.Rmd** file and the **.csv** data file generated by the simulation app. The analysis should assume that the data file is in the same directory as the report file. 

A template for the case study reports is available in our [GitHub repo](https://github.com/fcampelo/Design-and-Analysis-of-Experiments/tree/master/Report%20template).

Reports written in either Portuguese, English, or Spanish will be accepted.


### For undergrad (Systems Engineering) Students
Your report will be evaluated according to:

- Technical correctness;
- Correct use of language (grammar, orthography, etc.);

The report has no particular template. [R Markdown](http://rmarkdown.rstudio.com) is suggested, but not mandatory. Please send me the **.pdf** file (**NO** .doc, .odt, or other exotic formats please), the **.R** analysis file, and the **.csv** data file generated by the simulation app